# Generated by Django 5.0.6 on 2024-11-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_macdonals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='po',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mc_macdonals.order'),
        ),
        migrations.AddField(
            model_name='po',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mc_macdonals.product'),
        ),
    ]
