# Generated by Django 5.0.6 on 2024-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_macdonals', '0002_po_amount_po_order_po_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='mc_macdonals.PO', to='mc_macdonals.product'),
        ),
    ]
