# Generated by Django 5.1.2 on 2024-11-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_macdonals', '0003_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='po',
            old_name='amount',
            new_name='_amount',
        ),
    ]
